repos:
  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
  - repo: https://github.com/ambv/black
    rev: 23.3.0
    hooks:
      - id: black
  - repo: https://github.com/pycqa/flake8
    rev: 6.0.0
    hooks:
      - id: flake8
        args:
        - "--max-line-length=100"
        - "--per-file-ignores=__init__.py:F401"
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: "v1.2.0"
    hooks:
      - id: mypy
        additional_dependencies: [types-requests,types-PyYAML]
        language_version: python3.8
        exclude: ^docs/
default_language_version:
  python: python3
