name: Test Poetry Build

on:
  pull_request:
    branches: [ "main" ]

jobs:
  build-poetry:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - run: pipx install poetry

      - uses: actions/setup-python@v4
        with:
          python-version: 3.8
          cache: 'pipenv'

      - name: Install dependencies
        run: pip install .

      - name: Build package
        run: python -m build .
